Refactor: Beats handler to print cause details
[2020-11-30T12:53:38,997][INFO
][org.logstash.beats.BeatsHandler][main][beats-tls] [local:
0.0.0.0:5044, remote: 192.168.122.59:57466] Handling exception:
io.netty.handler.codec.DecoderException:
javax.net.ssl.SSLHandshakeException: General SSLEngine problem (caused
by: java.security.cert.CertPathValidatorException: Path does not chain
with any of the trust anchors)